print(True and True)
print(False and True)
print('It is false')
print(False and 0 != 0)
print('It is false')
print(not (True and False))
print('It is true')
print(not (10 == 1 or 1000 == 1000))
print('It is false')
print(not (10 == 1 or 1000 == 1000))
print('It is false')
print(not ("testing" == "testing" and "Zed" == "Cool Guy"))
print('It is true')
print(1 == 1 and (not ("testing" == 1 or 1 == 0)))
print('It is true')
print("chunky" == "bacon" and (not (3 == 4 or 3 == 3)))
print('It is false')
print(3 == 3 and (not ("testing" == "testing" or "Python" == "Fun")))
print('It is false')